name: Cronjob example

on: 
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # cada 5 min
      timezone: 'America/Mexico_City'
jobs:
  cronjob-schedule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Cronjob script
        run: echo "Ejecutando cronjob cada 5 minutos"